[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/usr/local/bin/start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
preDeployCommand = "php artisan migrate:fresh --seed"

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "error"