[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "php-fpm -D && nginx -g 'daemon off;'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
preDeployCommand = "php artisan migrate:fresh --seed --force"

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "error"